# Generated by Django 3.2.3 on 2022-12-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=2),
        ),
    ]
