# Generated by Django 3.2.3 on 2022-12-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapi', '0002_alter_user_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='names',
            new_name='name',
        ),
    ]
